/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChatServiceInternalModelsErrorResponse,
  ChatServiceInternalModelsPaginatedChatResponse,
  GetMessagesChannelIdParams
} from '../../schemas';

import { axiosInstance } from '../../axios-config';




/**
 * Get all chat messages for a specific channel (paginated)
 * @summary Get chat messages in a channel
 */
export const getMessagesChannelId = (
    id: number,
    params?: GetMessagesChannelIdParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ChatServiceInternalModelsPaginatedChatResponse>(
      {url: `/messages/channel/${id}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetMessagesChannelIdQueryKey = (id?: number,
    params?: GetMessagesChannelIdParams,) => {
    return [`/messages/channel/${id}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetMessagesChannelIdQueryOptions = <TData = Awaited<ReturnType<typeof getMessagesChannelId>>, TError = ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse>(id: number,
    params?: GetMessagesChannelIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesChannelId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMessagesChannelIdQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMessagesChannelId>>> = ({ signal }) => getMessagesChannelId(id,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMessagesChannelId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMessagesChannelIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMessagesChannelId>>>
export type GetMessagesChannelIdQueryError = ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse


export function useGetMessagesChannelId<TData = Awaited<ReturnType<typeof getMessagesChannelId>>, TError = ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse>(
 id: number,
    params: undefined |  GetMessagesChannelIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesChannelId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesChannelId>>,
          TError,
          Awaited<ReturnType<typeof getMessagesChannelId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesChannelId<TData = Awaited<ReturnType<typeof getMessagesChannelId>>, TError = ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse>(
 id: number,
    params?: GetMessagesChannelIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesChannelId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMessagesChannelId>>,
          TError,
          Awaited<ReturnType<typeof getMessagesChannelId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMessagesChannelId<TData = Awaited<ReturnType<typeof getMessagesChannelId>>, TError = ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse>(
 id: number,
    params?: GetMessagesChannelIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesChannelId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get chat messages in a channel
 */

export function useGetMessagesChannelId<TData = Awaited<ReturnType<typeof getMessagesChannelId>>, TError = ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse | ChatServiceInternalModelsErrorResponse>(
 id: number,
    params?: GetMessagesChannelIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMessagesChannelId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMessagesChannelIdQueryOptions(id,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



