/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { GormDeletedAt } from './gormDeletedAt';
import type { ChatServiceInternalModelsUser } from './chatServiceInternalModelsUser';

export interface ChatServiceInternalModelsChannel {
  created_at?: string;
  deleted_at?: GormDeletedAt;
  id?: number;
  members?: ChatServiceInternalModelsUser[];
  /** Name of the channel */
  name?: string;
  /** ID of the channel owner */
  ownerId?: number;
  /** Type of channel, either 'direct' or 'group' */
  type?: string;
  updated_at?: string;
}
