/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsDirectChannelResponse } from './chatServiceInternalModelsDirectChannelResponse';
import type { ChatServiceInternalModelsChannelResponse } from './chatServiceInternalModelsChannelResponse';

export interface ChatServiceInternalModelsUserChannelsResponse {
  /** List of channels of type 'direct' */
  direct?: ChatServiceInternalModelsDirectChannelResponse[];
  /** List of channels of type 'group' */
  group?: ChatServiceInternalModelsChannelResponse[];
}
