/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsUser } from './chatServiceInternalModelsUser';

export interface ChatServiceInternalModelsChannelDetailResponse {
  createdAt?: string;
  id?: number;
  /** List of members in the channel */
  members?: ChatServiceInternalModelsUser[];
  name?: string;
  ownerId?: number;
  type?: string;
}
