/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

export interface ChatServiceInternalModelsChannelResponse {
  id?: number;
  name?: string;
  ownerId?: number;
  type?: string;
}
