/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

export type ChatServiceInternalModelsChatRequestType = typeof ChatServiceInternalModelsChatRequestType[keyof typeof ChatServiceInternalModelsChatRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatServiceInternalModelsChatRequestType = {
  direct: 'direct',
  channel: 'channel',
} as const;
