/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsChatResponse } from './chatServiceInternalModelsChatResponse';

export interface ChatServiceInternalModelsPaginatedChatResponse {
  items?: ChatServiceInternalModelsChatResponse[];
  nextCursor?: number;
  total?: number;
}
