/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsCreateChannelRequestType } from './chatServiceInternalModelsCreateChannelRequestType';

export interface ChatServiceInternalModelsCreateChannelRequest {
  /** Optional for direct messages, required for group */
  name?: string;
  type: ChatServiceInternalModelsCreateChannelRequestType;
  /**
   * Minimum 2, maximum 4 users
   * @minItems 2
   * @maxItems 4
   */
  userIds: number[];
}
