/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

export enum ChatServiceInternalModelsCreateChannelRequestType {
  direct = 'direct',
  group = 'group',
};
