/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

export type ChatServiceInternalModelsCreateChannelRequestType = typeof ChatServiceInternalModelsCreateChannelRequestType[keyof typeof ChatServiceInternalModelsCreateChannelRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChatServiceInternalModelsCreateChannelRequestType = {
  direct: 'direct',
  group: 'group',
} as const;
