/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

export interface ChatServiceInternalModelsUpdateProfileRequest {
  /** Optional avatar URL */
  avatar?: string;
  /** Required current password for verification */
  current_password: string;
  /** @minLength 6 */
  password?: string;
  /**
   * @minLength 3
   * @maxLength 50
   */
  username?: string;
}
