/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */
import type { ChatServiceInternalModelsChannel } from './chatServiceInternalModelsChannel';
import type { GormDeletedAt } from './gormDeletedAt';

export interface ChatServiceInternalModelsUser {
  /** Avatar is optional and can be used to store a profile picture URL
It is not mandatory for the user to have an avatar. */
  avatar?: string;
  channels?: ChatServiceInternalModelsChannel[];
  created_at?: string;
  deleted_at?: GormDeletedAt;
  /** Unique email for the user */
  email?: string;
  id?: number;
  updated_at?: string;
  /** Username for the user */
  username?: string;
}
