/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

export interface ChatServiceInternalModelsChatResponse {
  /** channel */
  channelId?: number;
  /** timestamp of when the message was created */
  createdAt?: string;
  /** optional file name for media */
  fileName?: string;
  id?: number;
  /** Relate to type message */
  receiverId?: number;
  /** url string for avatar */
  senderAvatar?: string;
  /** ID of the user who sent the message */
  senderId?: number;
  /** Username of the sender */
  senderName?: string;
  /** free text message */
  text?: string;
  /** "direct" | "group" */
  type?: string;
  /** optional URL for media */
  url?: string;
}
