/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Notify Chat Service API
 * A RESTful API service for chat functionality
 * OpenAPI spec version: 1.0
 */

export type GetMessagesChannelIdParams = {
/**
 * Page size
 */
limit?: number;
/**
 * Cursor for infinite scroll (timestamp)
 */
before?: number;
};
