/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 */
import type { ModelsUserResponse } from './modelsUserResponse';

export interface ModelsLoginResponse {
  token?: string;
  user?: ModelsUserResponse;
}
