/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 */

export interface ModelsChannelListResponse {
  createdAt?: string;
  id?: number;
  name?: string;
  ownerId?: number;
  updatedAt?: string;
}
