/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 */

export type ModelsChatRequestType = typeof ModelsChatRequestType[keyof typeof ModelsChatRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsChatRequestType = {
  direct: 'direct',
  channel: 'channel',
} as const;
