/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Chat Service API
 * A real-time chat service API with WebSocket support for instant messaging, user management, friend system, and channel management.
 * OpenAPI spec version: 1.0
 */

export interface ModelsUserResponse {
  created_at?: string;
  email?: string;
  id?: number;
  username?: string;
}
