/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation
} from 'react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from 'react-query';

import type {
  ModelsLoginRequest,
  ModelsRegisterRequest,
  ModelsUserResponse,
  PostAuthLogin200,
  PostAuthLogin400,
  PostAuthLogin401,
  PostAuthLogin500,
  PostAuthRegister400,
  PostAuthRegister500
} from '../../schemas';





/**
 * Authenticate user with email and password
 * @summary User login
 */
export const postAuthLogin = (
    modelsLoginRequest: ModelsLoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostAuthLogin200>> => {
    
    
    return axios.post(
      `/auth/login`,
      modelsLoginRequest,options
    );
  }



export const getPostAuthLoginMutationOptions = <TError = AxiosError<PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: ModelsLoginRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: ModelsLoginRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: ModelsLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = ModelsLoginRequest
    export type PostAuthLoginMutationError = AxiosError<PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500>

    /**
 * @summary User login
 */
export const usePostAuthLogin = <TError = AxiosError<PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: ModelsLoginRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: ModelsLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthLoginMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Register a new user with username, email, and password
 * @summary Register a new user
 */
export const postAuthRegister = (
    modelsRegisterRequest: ModelsRegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ModelsUserResponse>> => {
    
    
    return axios.post(
      `/auth/register`,
      modelsRegisterRequest,options
    );
  }



export const getPostAuthRegisterMutationOptions = <TError = AxiosError<PostAuthRegister400 | PostAuthRegister500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: ModelsRegisterRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: ModelsRegisterRequest}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: ModelsRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = ModelsRegisterRequest
    export type PostAuthRegisterMutationError = AxiosError<PostAuthRegister400 | PostAuthRegister500>

    /**
 * @summary Register a new user
 */
export const usePostAuthRegister = <TError = AxiosError<PostAuthRegister400 | PostAuthRegister500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: ModelsRegisterRequest}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: ModelsRegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions );
    }
    