/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import {
  useMutation,
  useQuery
} from 'react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from 'react-query';

import type {
  DeleteChannelsId200,
  DeleteChannelsId401,
  DeleteChannelsId500,
  DeleteChannelsIdUser200,
  DeleteChannelsIdUser400,
  DeleteChannelsIdUser401,
  DeleteChannelsIdUser500,
  DeleteChannelsIdUserBody,
  GetChannels401,
  GetChannels500,
  GetChannelsId401,
  GetChannelsId404,
  ModelsChannelListResponse,
  ModelsChannelResponse,
  PostChannels400,
  PostChannels401,
  PostChannels500,
  PostChannelsBody,
  PostChannelsIdUser200,
  PostChannelsIdUser400,
  PostChannelsIdUser401,
  PostChannelsIdUser500,
  PostChannelsIdUserBody,
  PutChannelsId200,
  PutChannelsId400,
  PutChannelsId401,
  PutChannelsId500,
  PutChannelsIdBody,
  PutChannelsIdUser200,
  PutChannelsIdUser401,
  PutChannelsIdUser500
} from '../../schemas';





/**
 * Get all channels that the current user is a member of
 * @summary Get user's channels
 */
export const getChannels = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ModelsChannelListResponse[]>> => {
    
    
    return axios.get(
      `/channels/`,options
    );
  }


export const getGetChannelsQueryKey = () => {
    return [`/channels/`] as const;
    }

    
export const getGetChannelsQueryOptions = <TData = Awaited<ReturnType<typeof getChannels>>, TError = AxiosError<GetChannels401 | GetChannels500>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getChannels>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChannelsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChannels>>> = ({ signal }) => getChannels({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChannels>>, TError, TData> & { queryKey: QueryKey }
}

export type GetChannelsQueryResult = NonNullable<Awaited<ReturnType<typeof getChannels>>>
export type GetChannelsQueryError = AxiosError<GetChannels401 | GetChannels500>


/**
 * @summary Get user's channels
 */

export function useGetChannels<TData = Awaited<ReturnType<typeof getChannels>>, TError = AxiosError<GetChannels401 | GetChannels500>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getChannels>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetChannelsQueryOptions(options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create a new channel with the specified name
 * @summary Create a new channel
 */
export const postChannels = (
    postChannelsBody: PostChannelsBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ModelsChannelResponse>> => {
    
    
    return axios.post(
      `/channels/`,
      postChannelsBody,options
    );
  }



export const getPostChannelsMutationOptions = <TError = AxiosError<PostChannels400 | PostChannels401 | PostChannels500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannels>>, TError,{data: PostChannelsBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postChannels>>, TError,{data: PostChannelsBody}, TContext> => {

const mutationKey = ['postChannels'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChannels>>, {data: PostChannelsBody}> = (props) => {
          const {data} = props ?? {};

          return  postChannels(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostChannelsMutationResult = NonNullable<Awaited<ReturnType<typeof postChannels>>>
    export type PostChannelsMutationBody = PostChannelsBody
    export type PostChannelsMutationError = AxiosError<PostChannels400 | PostChannels401 | PostChannels500>

    /**
 * @summary Create a new channel
 */
export const usePostChannels = <TError = AxiosError<PostChannels400 | PostChannels401 | PostChannels500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannels>>, TError,{data: PostChannelsBody}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postChannels>>,
        TError,
        {data: PostChannelsBody},
        TContext
      > => {

      const mutationOptions = getPostChannelsMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Get detailed information about a specific channel
 * @summary Get channel by ID
 */
export const getChannelsId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ModelsChannelResponse>> => {
    
    
    return axios.get(
      `/channels/${id}`,options
    );
  }


export const getGetChannelsIdQueryKey = (id: number,) => {
    return [`/channels/${id}`] as const;
    }

    
export const getGetChannelsIdQueryOptions = <TData = Awaited<ReturnType<typeof getChannelsId>>, TError = AxiosError<GetChannelsId401 | GetChannelsId404>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getChannelsId>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetChannelsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getChannelsId>>> = ({ signal }) => getChannelsId(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getChannelsId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetChannelsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getChannelsId>>>
export type GetChannelsIdQueryError = AxiosError<GetChannelsId401 | GetChannelsId404>


/**
 * @summary Get channel by ID
 */

export function useGetChannelsId<TData = Awaited<ReturnType<typeof getChannelsId>>, TError = AxiosError<GetChannelsId401 | GetChannelsId404>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getChannelsId>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetChannelsIdQueryOptions(id,options)

  const query = useQuery(queryOptions ) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update the name of an existing channel
 * @summary Update channel
 */
export const putChannelsId = (
    id: number,
    putChannelsIdBody: PutChannelsIdBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PutChannelsId200>> => {
    
    
    return axios.put(
      `/channels/${id}`,
      putChannelsIdBody,options
    );
  }



export const getPutChannelsIdMutationOptions = <TError = AxiosError<PutChannelsId400 | PutChannelsId401 | PutChannelsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putChannelsId>>, TError,{id: number;data: PutChannelsIdBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putChannelsId>>, TError,{id: number;data: PutChannelsIdBody}, TContext> => {

const mutationKey = ['putChannelsId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putChannelsId>>, {id: number;data: PutChannelsIdBody}> = (props) => {
          const {id,data} = props ?? {};

          return  putChannelsId(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutChannelsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putChannelsId>>>
    export type PutChannelsIdMutationBody = PutChannelsIdBody
    export type PutChannelsIdMutationError = AxiosError<PutChannelsId400 | PutChannelsId401 | PutChannelsId500>

    /**
 * @summary Update channel
 */
export const usePutChannelsId = <TError = AxiosError<PutChannelsId400 | PutChannelsId401 | PutChannelsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putChannelsId>>, TError,{id: number;data: PutChannelsIdBody}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putChannelsId>>,
        TError,
        {id: number;data: PutChannelsIdBody},
        TContext
      > => {

      const mutationOptions = getPutChannelsIdMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Delete a channel (only channel owner can delete)
 * @summary Delete channel
 */
export const deleteChannelsId = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteChannelsId200>> => {
    
    
    return axios.delete(
      `/channels/${id}`,options
    );
  }



export const getDeleteChannelsIdMutationOptions = <TError = AxiosError<DeleteChannelsId401 | DeleteChannelsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChannelsId>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChannelsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteChannelsId'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChannelsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteChannelsId(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChannelsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChannelsId>>>
    
    export type DeleteChannelsIdMutationError = AxiosError<DeleteChannelsId401 | DeleteChannelsId500>

    /**
 * @summary Delete channel
 */
export const useDeleteChannelsId = <TError = AxiosError<DeleteChannelsId401 | DeleteChannelsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChannelsId>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteChannelsId>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteChannelsIdMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Remove the current user from a channel
 * @summary Leave channel
 */
export const putChannelsIdUser = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PutChannelsIdUser200>> => {
    
    
    return axios.put(
      `/channels/${id}/user`,undefined,options
    );
  }



export const getPutChannelsIdUserMutationOptions = <TError = AxiosError<PutChannelsIdUser401 | PutChannelsIdUser500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putChannelsIdUser>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putChannelsIdUser>>, TError,{id: number}, TContext> => {

const mutationKey = ['putChannelsIdUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putChannelsIdUser>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  putChannelsIdUser(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutChannelsIdUserMutationResult = NonNullable<Awaited<ReturnType<typeof putChannelsIdUser>>>
    
    export type PutChannelsIdUserMutationError = AxiosError<PutChannelsIdUser401 | PutChannelsIdUser500>

    /**
 * @summary Leave channel
 */
export const usePutChannelsIdUser = <TError = AxiosError<PutChannelsIdUser401 | PutChannelsIdUser500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putChannelsIdUser>>, TError,{id: number}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof putChannelsIdUser>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getPutChannelsIdUserMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Add a user to a channel (only channel owner can add users)
 * @summary Add user to channel
 */
export const postChannelsIdUser = (
    id: number,
    postChannelsIdUserBody: PostChannelsIdUserBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PostChannelsIdUser200>> => {
    
    
    return axios.post(
      `/channels/${id}/user`,
      postChannelsIdUserBody,options
    );
  }



export const getPostChannelsIdUserMutationOptions = <TError = AxiosError<PostChannelsIdUser400 | PostChannelsIdUser401 | PostChannelsIdUser500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelsIdUser>>, TError,{id: number;data: PostChannelsIdUserBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postChannelsIdUser>>, TError,{id: number;data: PostChannelsIdUserBody}, TContext> => {

const mutationKey = ['postChannelsIdUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postChannelsIdUser>>, {id: number;data: PostChannelsIdUserBody}> = (props) => {
          const {id,data} = props ?? {};

          return  postChannelsIdUser(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostChannelsIdUserMutationResult = NonNullable<Awaited<ReturnType<typeof postChannelsIdUser>>>
    export type PostChannelsIdUserMutationBody = PostChannelsIdUserBody
    export type PostChannelsIdUserMutationError = AxiosError<PostChannelsIdUser400 | PostChannelsIdUser401 | PostChannelsIdUser500>

    /**
 * @summary Add user to channel
 */
export const usePostChannelsIdUser = <TError = AxiosError<PostChannelsIdUser400 | PostChannelsIdUser401 | PostChannelsIdUser500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postChannelsIdUser>>, TError,{id: number;data: PostChannelsIdUserBody}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof postChannelsIdUser>>,
        TError,
        {id: number;data: PostChannelsIdUserBody},
        TContext
      > => {

      const mutationOptions = getPostChannelsIdUserMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Remove a user from a channel (only channel owner can remove users)
 * @summary Remove user from channel
 */
export const deleteChannelsIdUser = (
    id: number,
    deleteChannelsIdUserBody: DeleteChannelsIdUserBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DeleteChannelsIdUser200>> => {
    
    
    return axios.delete(
      `/channels/${id}/user`,{data:
      deleteChannelsIdUserBody, ...options}
    );
  }



export const getDeleteChannelsIdUserMutationOptions = <TError = AxiosError<DeleteChannelsIdUser400 | DeleteChannelsIdUser401 | DeleteChannelsIdUser500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChannelsIdUser>>, TError,{id: number;data: DeleteChannelsIdUserBody}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteChannelsIdUser>>, TError,{id: number;data: DeleteChannelsIdUserBody}, TContext> => {

const mutationKey = ['deleteChannelsIdUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteChannelsIdUser>>, {id: number;data: DeleteChannelsIdUserBody}> = (props) => {
          const {id,data} = props ?? {};

          return  deleteChannelsIdUser(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteChannelsIdUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteChannelsIdUser>>>
    export type DeleteChannelsIdUserMutationBody = DeleteChannelsIdUserBody
    export type DeleteChannelsIdUserMutationError = AxiosError<DeleteChannelsIdUser400 | DeleteChannelsIdUser401 | DeleteChannelsIdUser500>

    /**
 * @summary Remove user from channel
 */
export const useDeleteChannelsIdUser = <TError = AxiosError<DeleteChannelsIdUser400 | DeleteChannelsIdUser401 | DeleteChannelsIdUser500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteChannelsIdUser>>, TError,{id: number;data: DeleteChannelsIdUserBody}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteChannelsIdUser>>,
        TError,
        {id: number;data: DeleteChannelsIdUserBody},
        TContext
      > => {

      const mutationOptions = getDeleteChannelsIdUserMutationOptions(options);

      return useMutation(mutationOptions );
    }
    