/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 */
import {
  useMutation
} from 'react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from 'react-query';

import type {
  ModelsLoginRequest,
  ModelsLoginResponse,
  ModelsRegisterRequest,
  ModelsUserResponse,
  PostAuthLogin400,
  PostAuthLogin401,
  PostAuthLogin500,
  PostAuthRegister400,
  PostAuthRegister500
} from '../../schemas';

import { axiosInstance } from '../../axios-config';




/**
 * Authenticate user with email and password
 * @summary User login
 */
export const postAuthLogin = (
    modelsLoginRequest: ModelsLoginRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelsLoginResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelsLoginRequest, signal
    },
      );
    }
  


export const getPostAuthLoginMutationOptions = <TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: ModelsLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: ModelsLoginRequest}, TContext> => {

const mutationKey = ['postAuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, {data: ModelsLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = ModelsLoginRequest
    export type PostAuthLoginMutationError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500

    /**
 * @summary User login
 */
export const usePostAuthLogin = <TError = PostAuthLogin400 | PostAuthLogin401 | PostAuthLogin500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,{data: ModelsLoginRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        {data: ModelsLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthLoginMutationOptions(options);

      return useMutation(mutationOptions );
    }
    /**
 * Register a new user with username, email, and password
 * @summary Register a new user
 */
export const postAuthRegister = (
    modelsRegisterRequest: ModelsRegisterRequest,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ModelsUserResponse>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelsRegisterRequest, signal
    },
      );
    }
  


export const getPostAuthRegisterMutationOptions = <TError = PostAuthRegister400 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: ModelsRegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: ModelsRegisterRequest}, TContext> => {

const mutationKey = ['postAuthRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRegister>>, {data: ModelsRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postAuthRegister(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRegister>>>
    export type PostAuthRegisterMutationBody = ModelsRegisterRequest
    export type PostAuthRegisterMutationError = PostAuthRegister400 | PostAuthRegister500

    /**
 * @summary Register a new user
 */
export const usePostAuthRegister = <TError = PostAuthRegister400 | PostAuthRegister500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRegister>>, TError,{data: ModelsRegisterRequest}, TContext>, }
 ): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRegister>>,
        TError,
        {data: ModelsRegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions );
    }
    